<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>pagina prueba1</title>
</head>
<body>
   <h1>mi primera pagina hibrida studen ta ta ta ta ta ta ta taaaaaa taaaaaaaa taaaaaaaaaa taaaaaaaa</h1> 
<hr>
<?php
$variable=0;
echo "mi primer hola mundo con php";
//aqui creo mis opiniones 0 a 10

for($variable=0; $variable<=10; $variable++){
    echo"contador; ".$variable;
}
?>

</body>
</html>
